### ISSUE TITLE
Committee Page and/or Information on Committee

### ISSUE THREAD

**Issue by KommToby** [Watt-Esports/wattesports.co.uk#13]
Rundown of every committee member, their role in the Society, and some personal information

could be boring stuff such as
-epic picture of committee member-
name
age
favourite game
gamer name

etc

**Comment by Simber1** [comment]
Might be nice to have a list of all the old committees on that page too

**Comment by KommToby** [comment]
who do you think i am

**Comment by KommToby** [comment]
> Might be nice to have a list of all the old committees on that page too
This will be dealt with in #47

**Comment by KommToby** [comment]
The clickable committee will be dealt with in #45 , The current committee has been added to the about page so this issue is closed for time being
