### ISSUE TITLE
Custom Error 404 Page

### ISSUE THREAD

**Issue by KommToby** [Watt-Esports/wattesports.co.uk#46]
If for some reason the page doesn't load we have a backup page that is *maybe* avaliable in the root of the files, instead of in a deep cave of folders, so in case theres an error in the code, there is always a backup error page that it takes you to, with links back to the other pages.

**Comment by Simber1** [comment]
So you want a 404 page?

**Comment by KommToby** [comment]
> So you want a 404 page?

Yeah a 404 page. It's better than showing the regular ubuntu not found, and having a button on the 404 to return to the home site is helpful imo
