### ISSUE TITLE
Fix issue with footer being too far away from the bottom with images in it

### ISSUE THREAD

**Issue by Simber1** [Watt-Esports/wattesports.co.uk#5]
Pretty much title.

**Comment by KommToby** [comment]
I dont think we can fix this per se, we may have to make the footer an image with text stacked on top of it if we want it to be solid and not to move when we add stuff into it

but I think the best thing to do is to just re-adjust all of the images to the size of the text or resize the text to the size of the logos.

**Comment by KommToby** [comment]
Issue got fixed.. but the other half of the issue didnt oops

**Comment by Simber1** [comment]
Is this fixed now?
