### ISSUE TITLE
Cover all Image file types and sizes

### ISSUE THREAD

**Issue by Simber1** [Watt-Esports/wattesports.co.uk#72]
Currently most of the images are oversized and using low compression, web.dev recommends using one of the following: JPEG 2000, JPEG XR, or WebP.

**Comment by blueocto** [comment]
Be mindful of the support of these formats, before completely switching across to them.
Webp : https://caniuse.com/#feat=webp
JPEG 2000 : https://caniuse.com/#feat=jpeg2000
JPEG XR : https://caniuse.com/#feat=jpegxr
