### ISSUE TITLE
Footer doesn't go to the bottom on short pages

### ISSUE THREAD

**Issue by KommToby** [Watt-Esports/wattesports.co.uk#80]
![image](https://user-images.githubusercontent.com/12158645/81260982-1481bc80-9033-11ea-9582-a5f105ff1dde.png)
Pretty self explanatory, we need a way to make sure its at the bottom of the users window until they start scrolling.

**Comment by Simber1** [comment]
https://chrisbracco.com/css-sticky-footer-effect/. 

This might be able to fix this. If it hasn't been fixed by tonight I'll take a crack at it.

**Comment by KommToby** [comment]
> https://chrisbracco.com/css-sticky-footer-effect/.
> 
> This might be able to fix this. If it hasn't been fixed by tonight I'll take a crack at it.

I tried, and I did not succeed. Go for it

**Comment by Simber1** [comment]
Was fixed in #87, forgot to close.
