### ISSUE TITLE
Mobile: Zoom Out Hides Elements on about page.

### ISSUE THREAD

**Issue by KommToby** [Watt-Esports/wattesports.co.uk#86]
When zooming out on mobile it cuts off the header, footer, and content on the page.
![Screenshot_20200508-070052](https://user-images.githubusercontent.com/12158645/81375781-28dcbc80-90fa-11ea-85e1-8bb487978009.jpg)

**Comment by Simber1** [comment]
This only happens on the about page because the NSE and NUEL logos being side by side with fixed widths make the site too wide.
